<nav role="navigation" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">


         <?php
        if (! $hidemenus):
        ?>
            <button type="button" class="navbar-toggle" id="btn-toggle-navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        <?php
        endif;
        ?>

            <a class="navbar-brand" href="<?php echo $CFG->wwwroot;?>">
            Learning Space
            <!-- <?php echo $PAGE->pagelayout; ?> -->
            </a>
        </div>

        <!-- <div id="moodle-navbar" class="navbar-collapse collapse"> -->
        <div id="moodle-navbar" class="">
    <?php
        if (! $hidemenus):
    ?>
            <ul class="nav navbar-nav navbar-notresponsive visible-md visible-lg">
                <li><a href="<?php echo $CFG->wwwroot;?>">My Modules</a></li>

                <li class="dropdown"><a class="menu-item-resources dropdown-toggle" data-toggle="dropdown" href="#">Resources</a>
                    <ul class="dropdown-menu">
                            <li><a href="http://ask.fxplus.ac.uk/">ASK (Academic Skills)</a></li>
                            <li><a href="http://www.falmouth.ac.uk/facilities/the-compass">The Compass</a></li>
                            <li><a href="http://careerhub.falmouth.ac.uk">Careers and Employability</a></li>
                            <li><a href="http://inclusive.fxplus.ac.uk">Inclusive Learning</a></li>
                            <li><a href="http://www.falmouth.ac.uk/student-funding">Money Matters</a></li>
                            <li><a href="http://www.fxu.org.uk/">FXU</a></li>
                            <li><a href="http://www.fxplus.ac.uk/study/it-service-desk">IT Services</a></li>
                            <li><a href="http://library.fxplus.ac.uk/">Library and Information Services</a></li>
                            <li><a href="http://falmouthac.sharepoint.com/sa/SitePages/Assessment.aspx">Assessment Information</a></li>
                            <li><a href="http://learningspace.falmouth.ac.uk/course/view.php?id=686">Software Training</a></li>
                            <li><a href="http://learningspace.falmouth.ac.uk/course/view.php?id=714&section=1&section=1">Student Reps</a></li>
                            <li><a href="http://www.fxplus.ac.uk/study/student-support-services">Student Support</a></li>
                            <li class="divider"></li>
                            <li class="disabled">
                            <a href="http://etsupport.freshdesk.com/support/tickets/new" style="cursor:pointer">Not listed? Please make contact here</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <?php
            //echo $OUTPUT->custom_menu();
            ?>
            <?php
            // echo $OUTPUT->user_menu();
            ?>

            <ul class="nav navbar-nav navbar-notresponsive pull-right">
                <?php
                $pagebtn = $PAGE->button;
                if ($pagebtn !== '') {

                    // parse the html generated by moodle and add button classes to input.type=submit
                    /*
                    this is needed as the page button code produces an <input type='submit' which
                    is styled by
                    */
                    $dom = new DOMDocument;
                    $dom->loadHTML( $pagebtn );
                    $inputs = $dom->getElementsByTagName('input');
                    foreach ($inputs as $input) {
                        if ($input->getAttribute('type') == 'submit') {
                            $input->setAttribute('style', "display: none");

                            $dom_btn = $dom->createElement('button', $input->getAttribute('value'));
                            $dom_btn->setAttribute('type', 'submit');
                            $dom_btn->setAttribute('class', 'btn btn-navbar');

                            $input->parentNode->insertBefore( $dom_btn, $input );
                        }
                    }

                    $anchors = $dom->getElementsByTagName('a');
                    foreach ($anchors as $anchor) {
                        $anchor->setAttribute('class', 'btn btn-navbar');
                    }


                    $pagebtn = $dom->saveHTML();

                    echo "<li class='hidden-xs page-edit-btn-holder'>" . $pagebtn . "</li>";
                }
                ?>
                <li><a href="http://etsupport.freshdesk.com/support/solutions/158481">
                    <i class="fa fa-question-circle"></i>
                    <span class="hidden-xs">Help</span>
                </a></li>
                <?php
                //<li> echo $PAGE->headingmenu </li>
                ?>

                <?php
                // some renderers may not have this implemented - e.g. maintenance renderer
                if (method_exists($OUTPUT, 'user_menu')) {
                    echo $OUTPUT->user_menu();
                }
                ?>

            </ul>

        </div>
<?php
endif;
?>
    </div>
</nav>
